# 基础镜像
FROM nginx
# author
MAINTAINER gong.hanjin

# 挂载目录
VOLUME /home/ruoyi-vue-professional-ui
# 创建目录
RUN mkdir -p /home/ruoyi-vue-professional-ui
# 指定路径
WORKDIR /home/ruoyi-vue-professional-ui
# 复制conf文件到路径
#COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./dist /home/ruoyi-vue-professional-ui
